%% subsref enables to use calling atom.projects() with a projectName parameter
% This overloaded buildin function ensures to browse in the property of Atom
% class "projects" by project name instead of order.
%
%  INPUTS
%   S: The substruct generated by subsref, struct
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Filip Kozak, CTU in Prague, filip.kozak@antennatoolbox.com
