%% computeH calculates magnetic field at a point generated by current I
% This function evaluates matrix Nh such that H(rObs) = Nh*I is a magnetic
% field H at point rObs. Dyadic Green's function is used for evaluation, i.e.,
% H(r) = int(G(r-r') dot J(r')).
%
% INPUTS
%   mesh: mesh structure, struct [1 x 1]
%   basisFcns: basis functions, struc [1 x 1]
%   frequency: frequency, double [1 x Nf]
%   rObs: observation point, double [3 x 1]
%   quadOrder: quadrature order, integer {1 - 12}
%
% OUTPUTS
%   Nh: matrix generating H(rObs) = Nh*I, double [3 x nEdges x Nf]
%
% SYNTAX
%
% [Nh] = computeH(mesh, basisFcns, frequency, rObs, quadOrder)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2020, Lukas Jelinek, CTU in Prague, lukas.jelinek@antennatoolbox.com
% mcode
