%% computeE calculates electric field at a point generated by current I
% This function evaluates matrix Ne such that E(rObs) = Ne*I is an electric
% field E at point rObs. Dyadic Green's function is used for evaluation, i.e.,
% E(r) = int(G(r-r') dot J(r')).
%
% INPUTS
%   mesh: mesh structure, struct [1 x 1]
%   basisFcns: basis functions, struc [1 x 1]
%   frequency: frequency, double [1 x Nf]
%   rObs: observation point, double [3 x 1]
%   quadOrder: quadrature order, integer {1 - 12}
%
% OUTPUTS
%   Ne: matrix generating E(rObs) = Ne*I, double [3 x nEdges x Nf]
%
% SYNTAX
%
% [Ne] = computeE(mesh, basisFcns, frequency, rObs, quadOrder)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2020, Lukas Jelinek, CTU in Prague, lukas.jelinek@antennatoolbox.com
% mcode
