%% addCommand adds a command to the History.
% Accept a substruct (generated by subsref), convert it to a string and save it
% in the commandHistory.
%
%  INPUTS
%   S: input os build in subsref, struct
%
%  SYNTAX
%  addCommand(S)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Vladimir Peric, CTU in Prague
