%% createCommand creates a string of part of command into the History
% Accept a substruct (generated by subsref), convert it to a string.
%
%  INPUTS
%   S: input os build in subsref, struct
%
%  OUTPUTS
%   wholeCommand: part of command behind atom.project, char
%
%  SYNTAX
%
%  wholeCommand = createCommand(S)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Filip Kozak, CTU in Prague, filip.kozak@antennatoolbox.com
% (c) 2015, Vladimir Peric, CTU in Prague
