%% History stores the command history of a project
% Stores all substructs (generated by subsref calls) as strings, so they can
% be reevaluated or written to scripts.
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Filip Kozak, CTU in Prague, filip.kozak@antennatoolbox.com
