%% numArgumentsFromSubscript ...
% MATLAB calls it to determine the number of array elements involved in an
% indexing operation when the number of elements is greater than one.
%
%  INPUTS
%   projectObj: reference to Project object, Project [1 x 1]
%   s: struct generated by subsref method, struct
%   callingContext: Context in which result applies,
%                   matlab.mixin.util.IndexingContext [1 x 1]
%
%  OUTPUTS
%   n: number of vargout in subsref method, double [1 x 1]
%
%  SYNTAX
%
%  n = numArgumentsFromSubscript(projectObj,s,callingContext)
%
% Method returns the number of expected inputs to subsasgn or the number of
% expected outputs from subsref.
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Filip Kozak, CTU in Prague, filip.kozak@antennatoolbox.com
