%% subsref is overloaded buildin function to catch every call and log them
% All calls in the project need to be logged in the history property, so they
% can be reevaluated or transformed to a script. This requires the overloading
% of subsref. Functions which shouldn't be recorded in the history NEED to be
% specified here and handled correctly. This function shouldn't ever be called
% directly.
%
%  INPUTS
%   S: The substruct generated by subsref, struct
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Miloslav Capek, CTU in Prague, miloslav.capek@antennatoolbox.com
% (c) 2015, Filip Kozak, CTU in Prague, filip.kozak@antennatoolbox.com
% (c) 2015, Vladimir Peric, CTU in Prague
