%% Example how to use GEP without AToM with custom inner solver
%
% see also functions myMoM2D.m and myMoM2DSolve.m

% create GEP object
myGEP = models.solvers.GEP.GEP;
% set properties
myGEP.setProperties(...
   'innerSolver', 'custom',...
   'innerSolverHndl', '@(objGEP) myMoM2D(objGEP)',...
   'innerSolverSolve', ['@(innerSolver, frequencyList, waitbar) '...
      'myMoM2DSolve(innerSolver, frequencyList, waitbar)'],...
   'innerSolverGetA', '@(innerSolver) innerSolver.X',...
   'innerSolverGetB', '@(innerSolver) innerSolver.R',...
   'nModes', 30,...
   'AFSnIterations', 3,...
   'AFSgoal', 'crossing');
% frequency list
frequencyList = linspace(1, 3, 21) .* 1e8;
% solve GEP
myGEP.solve(frequencyList);