function mySolver = myMoM2DSolve(mySolver, frequencyList, waitbar)
%% Solve inner solver for example GEP_withoutAToM_MoM2D.m

% inputs for MoM
gaps = [];
waves = [];
symmetries = [];
settings = struct(...
   'quadOrder', 1, ...
   'nBatchMax', 5e3, ...
   'nWorkers', 0, ...
   'resultPath', pwd, ...
   'resultsInRAM', true, ...
   'resultsInFile', false, ...
   'verbosity', 2);
requests = {'mesh', 'basisFcns', 'zMat'};

% solve MoM
Res = models.solvers.MoM2D.solve(mySolver.mesh, frequencyList, gaps, ...
   waves, symmetries, settings, requests, waitbar);

% set outputs
mySolver.X = imag(Res.zMat.data);
mySolver.R = real(Res.zMat.data);