%% getArrowData create data matrix which containts following data
% [triaNumber PX PY PZ QX QY QZ],
% i.e. centre point (origin of every arrow) and vector describing each
% arrow.
%
% INPUTS
%  arrow: arrow field from structure handles generated by AToM results,
%         Patch [1 x 1]
%
% OUTPUTS
%  data: data matrix in the specific format,  double [N x 7]
%
% SYNTAX
%  data = results.export.getArrowData(handles.arrow(3))
%
% Included in AToM, info@antennatoolbox.com
% (c) 2016, Miloslav Capek, CTU in Prague, miloslav.capek@antennatoolbox.com
% (c) 2017, Vit Losenicky, CTU in Prague, vit.losenicky@antennatoolbox.com
