%% getTriangleData create data matrix which containts following data
% [triaNumber P1X P1Y P1Z P2X P2Y P2Z P3X P3Y P3Z ColorR ColorG ColorB],
% i.e. triandle IDs, vertices coordinates and color of fill
%
% INPUTS
%  triangles: triangles field from structure handles generated by AToM
%  results, Patch [1 x 1]
%
% OUTPUTS
%  data: data matrix in the specific format,  double [N x 13]
%
% SYNTAX
%  data = results.export.getTriangleData(handles.triangles)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2016, Miloslav Capek, CTU in Prague, miloslav.capek@antennatoolbox.com
% (c) 2017, Vit Losenicky, CTU in Prague, vit.losenicky@antennatoolbox.com
