%% surf2txt automatically process handles structure from AToM Results
% Data from handle structure generated in AToM Results is saved into txt
% file in specific format (saved data and its format specified below..
%
% Saved objects
%  triangles with colormap
%  quiver
%
% Output txt format
%  _Cmap:     [triaNumber X1 Y1 Z1 X2 Y2 Z2 X3 Y3 Z3 colorR colorG colorB]
%  _Quiver:   [triaNumber X Y Z U V W]
%
% INPUTS
%  handles: handle structure generated by AToM Results, struct [1 x 1]
%
% INPUT parameters
%  'filename'  sets the output file name, char [1 x N]
%  'scale'     sets the enlargement of the object, double [1 x 1],
%              default value: 1
%
%  'autoshift' sets automatic shift to (0,0) for left bottom point,
%              logical [1 x 1], default value: false
%  'shift'     sets shift defined by vector, double [1 x 3]
%
% SYNTAX
%  results.export.surf2txt(handles)
%  results.export.surf2txt(handles, 'filename', 'testFile')
%  results.export.surf2txt(handles, 'scale', 2.7)
%  results.export.surf2txt(handles, 'scale', 2.7, 'autoshift', true)
%  results.export.surf2txt(handles, 'scale', 2.7, 'shift', [1 0 0])
%
% Included in AToM, info@antennatoolbox.com
% (c) 2016, Miloslav Capek, CTU in Prague, miloslav.capek@antennatoolbox.com
% (c) 2017, Vit Losenicky, CTU in Prague, vit.losenicky@antennatoolbox.com
