%% addFigure adds figure into lists
% Adds figure reference and handles structure into appropriate preferences of
% FigureManager.
%
%  INPUTS
%   obj: FigureManager object, [1 x 1]
%   handles: structure of graphical object generated by plotting function,
%   structure [1 x 1]
%
%  SYNTAX
%   figureManager.addFigure(handles)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2017, Vit Losenicky, CTU in Prague, vit.losenicky@antennatoolbox.com
