%% updateFigure updates handles structure in list
% This method updates structure of graphical objects.
% It should be called when something is added into figure (removed from figure).
%
%  INPUTS
%   obj: FigureManager object, [1 x 1]
%   handles: structure of graphical object generated by plotting function,
%   structure [1 x 1]
%
%  SYNTAX
%   figureManager.updateFigure(handles)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2017, Vit Losenicky, CTU in Prague, vit.losenicky@antennatoolbox.com
