%% updateContent controls position of figures
% This method stores content of each figure. It is used, when figure is
% redrawed by the "Explore" function.
%
%  INPUTS
%   obj: FigureManager object, [1 x 1]
%   handles: structure of graphical object generated by plotting function,
%   structure [1 x 1]
%   newHandle: functionHandle, [1 x 1]
%   slotName: name of slot, char [1 x N]
%   listPointName: name of listPoint, char [1 x N]
%   dataName: name of data, char [1 x N]
%
%  SYNTAX
%   figureManager.updateContent(handles, newHandle, slotName, ...
%   listPointName, dataName)
%
% Included in AToM, info@antennatoolbox.com
% (c) 2017, Vit Losenicky, CTU in Prague, vit.losenicky@antennatoolbox.com
