%% validateString validates input string with better error message
% This function reduces error stack generated by validatestring().
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Vladimir Sedenka, BUT, vladimir.sedenka@antennatoolbox.com
