%% validateAttributes validates input attributes with better error message
% This function reduces error stack generated by validateattributes().
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Vladimir Sedenka, BUT, vladimir.sedenka@antennatoolbox.com
