function validStr = validateString(obj, varargin)
%% validateString validates input string with better error message
% This function reduces error stack generated by validatestring().
%
% Included in AToM, info@antennatoolbox.com
% (c) 2015, Vladimir Sedenka, BUT, vladimir.sedenka@antennatoolbox.com

try
   validStr = validatestring(varargin{:});  % pass everything as is
catch ME
   errorStruct = struct(...
      'identifier', sprintf('ERROR:%s', ME.identifier), ...
      'message', ME.message);
   if ~isempty(inputname(2))
      errorStruct.message = sprintf('Problem with input argument "%s". %s', ...
         inputname(2), errorStruct.message);
   end
   obj.deliver(errorStruct);
end

end

